version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    networks:
      - webapp
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    container_name: backend
    image: backend
    ports:
      - 5500:5500
      - 5555:5555
      - 5501:5501
    environment:
      - DB_URL=postgresql://swypf:secret@db:5432/postgres_db?schema=public
    volumes:
      - ./backend/prisma:/backend/prisma
      - ./backend/src:/backend/src
    networks:
      - database
      - webapp
    depends_on:
      - db
  #    command: ['./start.sh' ]

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=swypf
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres_db
    networks:
      - database

volumes:
  db_volume:
  front_volume:

networks:
  database:
    driver: bridge
  webapp:
    driver: bridge
