export const ERR_ACCEPT_FREQ =		"Error accepting friend request."
export const ERR_ALRDY_REQD =		"Error sending friend request: Request already pending."
export const ERR_NO_FREQ1 = 		"Error accepting friend request: No such id found in incoming requests."
export const ERR_NO_FREQ2 = 		"Error accepting friend request: No such id found in outgoing requests."
export const ERR_DECL_FREQ =		"Error declining friend request."
export const ERR_ALRDY_BLOCKED = 	"Error blocking user: already blocked."
export const ERR_NAMETAKEN =		"Name already in use. Choose a different name."
export const ERR_NAMECHANGE =		"Error changing name."
export const ERR_AVATAR_NULL = 		"Invalid file. Avatar not changed."
export const ERR_INVALFILETYPE =	"Invalid file type."

export const INFO_ACCEPT_FREQ = 	"Friend request accepted."
export const INFO_ALRDY_FR1 = 		"Accept friend request: already friends (thisId)."
export const INFO_ALRDY_FR2 = 		"Accept friend request: already friends (otherId)."
export const INFO_SEND_FREQ = 		"Friend request sent."
export const INFO_FREQ_CANCEL = 	"Friend request canceled."
export const INFO_DECL_FREQ = 		"Friend request declined."
export const INFO_FREQ_ALRDYSENT1 = "Friend request: already sent (friendReq_in)."
export const INFO_FREQ_ALRDYSENT2 = "Friend request: already sent (friendReq_out)."
export const INFO_BLOCK = 			"User blocked."
export const INFO_UNBLOCK = 		"User unblocked."
export const INFO_BLOCK_RM = 		"User blocked and removed from friends."
export const INFO_BLOCK_CANCEL = 	"User blocked and friend request canceled."
export const INFO_RM = 				"User removed from friends."
export const INFO_NAMECHANGED = 	"Name changed."
export const INFO_AVATARCHANGED = 	"Avatar changed."

