export const ERR_ACCEPT_FREQ =		"Error accepting friend request."
export const ERR_ALRDY_REQD =		"Error sending friend request: Request already pending."
export const ERR_NO_FREQ = 			"Error accepting friend request: No such id found in incoming requests."
export const ERR_DECL_FREQ =		"Error declining friend request."
export const ERR_ALRDY_BLOCKED = 	"Error blocking user: already blocked."
export const ERR_NOT_BLOCKED = 		"Error unblocking user: user is not blocked."

export const INFO_ACCEPT_FREQ = 	"Friend request accepted."
export const INFO_SEND_FREQ = 		"Friend request sent."
export const INFO_FREQ_CANCEL = 	"Friend request canceled."
export const INFO_DECL_FREQ = 		"Friend request declined."
export const INFO_BLOCK = 			"User blocked."
export const INFO_UNBLOCK = 		"User unblocked."
export const INFO_BLOCK_RM = 		"User blocked and removed from friends."
export const INFO_RM = 				"User removed from friends."
